my_blog_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

logout:
    path: logout

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

